### PR TITLE
Resolve canonical WebFinger subjects of remote actors

### LINKED ISSUE #285: Custom WebFinger domain (à la Mastodon's `LOCAL_DOMAIN`)
Mastodon uses (misleadingly named IMO) [`LOCAL_DOMAIN`] environment variable value to set the domain part of canonical WebFinger `subject`s of the server. It would be great if Kitsune supported a similar configuration.

[`LOCAL_DOMAIN`]: <https://docs.joinmastodon.org/admin/config/#local_domain>

Suppose Alice is running a  Mastodon server at `social.alice.example` domain. Naively, Alice's handle name would be `@alice@social.alice.example`, but why bother with the `social.` subdomain? In the world of e-mail, Alice can run an SMTP server at `smtp.alice.example` and receive mails as `alice@alice.example` by setting appropriate DNS records. `LOCAL_DOMAIN` works just like that: Alice's account will be recognized as `@alice@alice.example` by setting `LOCAL_DOMAIN` to `alice.example` (and setting up appropriate HTTP redirections in `alice.example` domain), while the actual Mastodon server is running at `social.alice.example`.

[`social.treehouse.systems`](<https://social.treehouse.systems>) is an example of such a Mastodon server. When you look up <https://social.treehouse.systems/@ariadne> in another Mastodon server, the account will be shown as `@ariadne@treehouse.systems` instead of `@ariadne@social.treehouse.systems`. But how does the other Mastodon server know that `@ariadne@treehouse.systems` is the canonical handle?

Let's follow the discovery process by hand. First, fetch the Activity Streams object at <https://social.treehouse.systems/@ariadne>, which tells us that `ariadne` is the actor's `preferredUsername`. Then, perform a WebFinger query <https://social.treehouse.systems/.well-known/webfinger?resource=acct:ariadne@social.treehouse.systems>, and we get a JRD document with its `subject` field being `acct:ariadne@treehouse.systems`. But since the domain part of the `subject` is different from the ActivityPub actor's domain, we need to verify with `treehouse.systems` by performing another WebFinger query <https://treehouse.systems/.well-known/webfinger?resource=acct:ariadne@treehouse.systems>, just in case `social.treehouse.systems` is making a bogus claim to the authority over the other domain. If the second WebFinger query result agrees with the first one (or simply redirects back to <https://social.treehouse.systems/.well-known/webfinger?resource=acct:ariadne@treehouse.systems>), then we can finally confirm that `acct:ariadne@treehouse.systems` is the canonical subject!

To sum up, in order to support a configuration like `LOCAL_DOMAIN`, the WebFinger handler needs to accept both the server's actual domain and the configured domain. I haven't read the code throughly, but some code depending on `kitsune::service::UrlService::domain` might also need to be updated. At least, [`uri` field of `V1::Instance`][v1-instance-uri] should use the `LOCAL_DOMAIN` value.

[v1-instance-uri]: <https://docs.joinmastodon.org/entities/V1_Instance/#uri>

I think this might also be a good fit for Shuttle's Hobby plan where you cannot bring your own domain (cf. #78). Although you would still be locked into Shuttle's domain in terms of ActivityPub object IDs, at least the handle names would look much better this way.

### PR DESCRIPTION
**Pull request by tesaguri**
This patch is intended to make the ActivityPub fetcher resolve the canonical WebFinger subjects (`acct`) of remote actors and make the APIs return the resolved `acct`s so that the frontend and clients can display them.

Closes #285.

~Currently, this only updates the WebFinger resolver implementation to resolve canonical subjects and is not ready for merging yet since the ActivityPub fetcher implementation is yet to be updated. For now, the resolver is only doing more number of requests in vain.~ (Edit: Fixed in 2cea6ebe2ae3f810200a7b2ec402b819e8462a05)

That being said, I think this is at a good checkpoint for reviewing now.

### CODE REVIEW

**Comment by tesaguri** [comment]
The ActivityPub actor fetcher now resolves the WebFinger `acct` name.

The patch replaces `accounts.domain` column with the resolved WebFinger domain name. Is that desirable? Or should we keep the original domain name of ActivityPub actor URI, and store the WebFinger domain in a separate column?

Also, it doesn't apply the federation filter to the WebFinger domain name yet.

**Comment by aumetra** [comment]
Thanks for the PR, I'll be having a look this evening. Work has been keeping me pretty busy the last few days

**Comment by tesaguri** [comment]
Another thing to consider: the new fetcher implementation falls back to `{preferredUsername}@{domain}` to keep WebFinger optional. But this could potentially lead to an inconsistent behavior if a server has multiple actors with a same `preferredUsername`, which is weird but possible.

This wouldn't be a problem if we mandate WebFinger like Mastodon does, because there is a guaranteed one-to-one correspondence between an ActivityPub actor and a WebFinger resource as a WebFinger resource only points to a single ActivityPub actor and an ActivityPub actor only points to a single `acct:` URI.

**Comment by aumetra** [comment]
> The patch replaces accounts.domain column with the resolved WebFinger domain name. Is that desirable?

I think that's fine. The column is only ever used for the Webfinger-like resolver and for enforcing the "one username per instance" rule that we internally enforce to keep some consistency.

**Comment by aumetra** [comment]
> Another thing to consider: the new fetcher implementation falls back to {preferredUsername}@{domain} to keep WebFinger optional. But this could potentially lead to an inconsistent behavior if a server has multiple actors with a same preferredUsername, which is weird but possible

That sounds like a very edge edgecase, no? I haven't really seen any services that don't have `preferredUsername` as a per-domain unique value.

**Comment by tesaguri** [comment]
> That sounds like a very edge edgecase, no? I haven't really seen any services that don't have preferredUsername as a per-domain unique value.

Yeah it's a hypothetical talk and I think it's fine to just throw `UniqueViolation` or something in that case. Even though the spec allows it to happen, we (and many implementations out there) already reject a lot of possible-in-spec cases after all (e.g. some Activity Streams `Object` properties are considered virtually required in practice, whereas the spec [says][as-core-object] that all properties (including the `id` and `type`!) are "optional" (not the upper-case OPTIONAL though)).

The closest real-world example I know of is (now-unmaintained) Wildebeest, where usernames are treated as case-sensitive so multiple actors with a same username modulo casing can exist in a same server. But Kitsune as it stands also treats username in the same way AFAICT, and even if we were to treat *local* usernames as case-insensitive, we could still handle *remote* usernames case-sensitively, so it wouldn't be a problem in that case either.

[as-core-object]: <https://www.w3.org/TR/activitystreams-core/#object>

**Comment by aumetra** [comment]
> But Kitsune as it stands also treats username in the same way AFAICT

Yeah, we do at the moment, but I feel like we should probably change that behaviour. Just way too confusing.

**Review by aumetra — APPROVED** [review]
Looks good! Thanks for the PR

**Pull request merged**
