### PR TITLE
Added service example file

### PR DESCRIPTION
**Pull request by SlimeyIceCream**
I added a systemd service example file.
I dont know how/if you can have comments in a .service files so I just did a bit of DIY....

I dont know how to(trying to figure it out but ill probably go to bed first) add files to the left sidebar properly, but if you make a page for basic systemd usage ill fill it out.

### CODE REVIEW

**Comment by aumetra** [comment]
Thank you for adding this. I did some small adjustments:

- Moved it into a `contrib` directory. This is the directory I'd like to have all kinds of configurations for external services, such as Redis, Postgres, NGINX, Caddy, systemd, etc.
- Renamed it to `kitsune.service`
- Converted the instructions between the `!!!` to regular comments
- Changed the wording of the instructions (away from the more uncertain ("can", "believe", etc.) language to more direct and concise language)

Let me know if that's okay with you and whether that's the final revision from your side

If it isn't, GitHub has a feature for work-in-progress pull requests, so feel free to mark it as such and just unmark and request a review when you feel it's done!

**Comment by aumetra** [comment]
By the way, if you feel like an example Caddy/NGINX/whatever configuration would be useful, feel free to open PRs adding them to the `contrib/` directory

**Comment by SlimeyIceCream** [comment]
> Thank you for adding this. I did some small adjustments:
> 
>     * Moved it into a `contrib` directory. This is the directory I'd like to have all kinds of configurations for external services, such as Redis, Postgres, NGINX, Caddy, systemd, etc.
> 
>     * Renamed it to `kitsune.service`
> 
>     * Converted the instructions between the `!!!` to regular comments
> 
>     * Changed the wording of the instructions (away from the more uncertain ("can", "believe", etc.) language to more direct and concise language)
> 
> 
> Let me know if that's okay with you and whether that's the final revision from your side
> 
> If it isn't, GitHub has a feature for work-in-progress pull requests, so feel free to mark it as such, and just unmark and request a review when you feel it's done!

Its fine! Thanks for fixing it up

**Comment by aumetra** [comment]
You need to keep it open for me to be able to merge it :D

**Comment by SlimeyIceCream** [comment]
> You need to keep it open for me to be able to merge it :D

Sorry I have no idea how github pull requests work lol, thought it already got merged lol

**Comment by aumetra** [comment]
No problem! Also don't worry about the test fail, it's a cache issue. I'll clear the cache and requeue the check

**Pull request merged**
